import Header from '@/components/header'
import './globals.css'
import { Providers } from "./providers";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light bg-bg text-txt'>
      <body>
        <Providers>
          <header className='wn fixed bottom-0 z-50'><Header /></header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
