name: Docker Build

on:
  push:
    braches:
      - develop
      - main
    tags:
      - "*"
  pull_request:
  release:
    types:
      - created
      - published
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Docker Image"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PAT }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            maintainer=Jake Landers
            org.opencontainers.image.description=The docker image for the workoutnotepad site
            org.opencontainers.image.vendor=Landersweb LLC
            image.name=ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
      
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.output.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      ########################################################
      # PRODUCTION ONLY STEPS
      ########################################################

      - name: PRODUCTION STEP - Install Regctl for registry management
        if: github.event_name == 'release' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        id: install_regctl
        uses: iarekylew00t/regctl-installer@v3

      - name: PRODUCTION STEP - Publish Image
        if: github.event_name == 'release' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        id: publish_image
        run: |
          regctl registry set --tls=disabled ghcr.io
          regctl image copy \
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.version }} \
            ghcr.io/${{ github.repository }}:latest